// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umfg.Repositorio.Classes;

#nullable disable

namespace Umfg.Repositorio.Migrations
{
    [DbContext(typeof(MySqlDataBaseContext))]
    [Migration("20230511233232_Migration_1_0_0")]
    partial class Migration_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Umfg.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CD_BARRA")
                        .HasAnnotation("Relational:JsonPropertyName", "codigoBarra");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_PRODUTO")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_PRODUTO")
                        .HasAnnotation("Relational:JsonPropertyName", "valor");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
