// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umfg.Repositorio.Classes;

#nullable disable

namespace Umfg.Repositorio.Migrations
{
    [DbContext(typeof(MySqlDataBaseContext))]
    partial class MySqlDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Umfg.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext")
                        .HasColumnName("DOCUMENTO")
                        .HasAnnotation("Relational:JsonPropertyName", "documento");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("NOME")
                        .HasAnnotation("Relational:JsonPropertyName", "nome");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("ENDERECO")
                        .HasAnnotation("Relational:JsonPropertyName", "endereco");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext")
                        .HasColumnName("CELULAR")
                        .HasAnnotation("Relational:JsonPropertyName", "celular");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext")
                        .HasColumnName("OBSERVACAO")
                        .HasAnnotation("Relational:JsonPropertyName", "observacao");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
